In [21]:
import os
import sys
import numpy as np

sys.path.append('../')
from utils import load_all_fmri_for_subject
from dataloaders import NSDImageDataset

In [23]:
nsd_dataset = NSDImageDataset(nsd_path='../../StableDiffusionReconstruction/nsd')

print(nsd_dataset[0].shape)

[[[212 212 204]
  [205 205 197]
  [203 203 195]
  ...
  [138 142 125]
  [144 144 128]
  [109 103  91]]

 [[205 205 197]
  [200 200 192]
  [200 200 192]
  ...
  [138 144 133]
  [147 154 145]
  [ 99 107 102]]

 [[204 204 196]
  [200 200 192]
  [201 201 193]
  ...
  [139 148 138]
  [105 118 114]
  [160 174 180]]

 ...

 [[113  93  85]
  [140 109  82]
  [172 126  71]
  ...
  [156 157 181]
  [174 177 184]
  [190 177 164]]

 [[117  98  90]
  [140 109  84]
  [171 125  78]
  ...
  [144 146 164]
  [180 182 185]
  [199 184 168]]

 [[120 101  90]
  [139 108  84]
  [174 128  82]
  ...
  [149 154 163]
  [177 179 181]
  [204 187 178]]]


NameError: name 'load_img_from_arr' is not defined